locale:
  prefix: "&7[&a&lCreative&fCraft&7]&f"
  message: "&7[&8&l✚&7]&7 {0} executed {1}"
  toggle-on: "You are now &aspying&f on commands network-wide."
  toggle-off: "You are no longer &aspying&f on commands network-wide."
spies: {}
